version: "3"

services:
    node:
          container_name: metrics-alarm-api
          restart: always
          build: .
          ports:
              - "8080:8080"
          links: 
              - mongodb
          environment:
            NODE_ENV: production
    mongodb:
          container_name: mongodb-database
          image: mongo
          ports:
              - "27017:27017"


